### PR TITLE
Handle json api and graphql

### PR DESCRIPTION
**Pull request by dkuku**
Few fixes:
- update `curl_req`, I added handling of `--data-raw`to `curl_req` because that's what firefox returns when I copy request as curl
- fix headers handling, the headers were empty for me on the page because req parses it to a list and not strings.
- handle [json_api ](https://jsonapi.org/format/)media type. Some of the apps I work on use this.
- handle [graphql](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#accept) media type. 
The mediatypes may be longer: `application/json;charset=UTF-8` - consider maybe storing it as generic_type  like json + original string 
Screenshot from 2024-11-28 19-52-52
Screenshot from 2024-11-28 19-53-12

### CODE REVIEW

**Comment by dkuku** [comment]
@acalejos Hey, this is ready for review.

**Comment by acalejos** [comment]
Hey, thanks so much for the PR! Everything looks good to me so I'll go ahead and pull it in. Not sure when the next hex publish will be, but if I find that I don't have any additions I plan on making in the next few weeks I'll just go ahead and push a minor with these updates.

**Comment by dkuku** [comment]
👋🏻👋🏻👋🏻 friendly reminder

**Comment by acalejos** [comment]
> 👋🏻👋🏻👋🏻 friendly reminder 

Thanks for the reminder. I'll push a release by end of the day

**Pull request merged**
